window.esdocSearchIndex = [
  [
    "wootils/wootils/shared/apiclient.js~apiclient",
    "class/wootils/shared/apiClient.js~APIClient.html",
    "<span>APIClient</span> <span class=\"search-result-import-path\">wootils/wootils/shared/apiClient.js</span>",
    "class"
  ],
  [
    "wootils/wootils/node/appconfiguration.js~appconfiguration",
    "class/wootils/node/appConfiguration.js~AppConfiguration.html",
    "<span>AppConfiguration</span> <span class=\"search-result-import-path\">wootils/wootils/node/appConfiguration.js</span>",
    "class"
  ],
  [
    "wootils/wootils/node/environmentutils.js~environmentutils",
    "class/wootils/node/environmentUtils.js~EnvironmentUtils.html",
    "<span>EnvironmentUtils</span> <span class=\"search-result-import-path\">wootils/wootils/node/environmentUtils.js</span>",
    "class"
  ],
  [
    "wootils/wootils/node/errorhandler.js~errorhandler",
    "class/wootils/node/errorHandler.js~ErrorHandler.html",
    "<span>ErrorHandler</span> <span class=\"search-result-import-path\">wootils/wootils/node/errorHandler.js</span>",
    "class"
  ],
  [
    "wootils/wootils/shared/eventshub.js~eventshub",
    "class/wootils/shared/eventsHub.js~EventsHub.html",
    "<span>EventsHub</span> <span class=\"search-result-import-path\">wootils/wootils/shared/eventsHub.js</span>",
    "class"
  ],
  [
    "wootils/wootils/node/logger.js~logger",
    "class/wootils/node/logger.js~Logger.html",
    "<span>Logger</span> <span class=\"search-result-import-path\">wootils/wootils/node/logger.js</span>",
    "class"
  ],
  [
    "wootils/wootils/node/pathutils.js~pathutils",
    "class/wootils/node/pathUtils.js~PathUtils.html",
    "<span>PathUtils</span> <span class=\"search-result-import-path\">wootils/wootils/node/pathUtils.js</span>",
    "class"
  ],
  [
    "wootils/wootils/node/appconfiguration.js~appconfiguration",
    "function/index.html#static-function-appConfiguration",
    "<span>appConfiguration</span> <span class=\"search-result-import-path\">wootils/wootils/node/appConfiguration.js</span>",
    "function"
  ],
  [
    "wootils/wootils/node/logger.js~applogger",
    "variable/index.html#static-variable-appLogger",
    "<span>appLogger</span> <span class=\"search-result-import-path\">wootils/wootils/node/logger.js</span>",
    "variable"
  ],
  [
    "wootils/wootils/node/logger.js~apploggerwithoptions",
    "function/index.html#static-function-appLoggerWithOptions",
    "<span>appLoggerWithOptions</span> <span class=\"search-result-import-path\">wootils/wootils/node/logger.js</span>",
    "function"
  ],
  [
    "wootils/wootils/shared/deferred.js~deferred",
    "function/index.html#static-function-deferred",
    "<span>deferred</span> <span class=\"search-result-import-path\">wootils/wootils/shared/deferred.js</span>",
    "function"
  ],
  [
    "wootils/wootils/node/environmentutils.js~environmentutils",
    "variable/index.html#static-variable-environmentUtils",
    "<span>environmentUtils</span> <span class=\"search-result-import-path\">wootils/wootils/node/environmentUtils.js</span>",
    "variable"
  ],
  [
    "wootils/wootils/node/errorhandler.js~errorhandler",
    "variable/index.html#static-variable-errorHandler",
    "<span>errorHandler</span> <span class=\"search-result-import-path\">wootils/wootils/node/errorHandler.js</span>",
    "variable"
  ],
  [
    "wootils/wootils/node/errorhandler.js~errorhandlerwithoptions",
    "function/index.html#static-function-errorHandlerWithOptions",
    "<span>errorHandlerWithOptions</span> <span class=\"search-result-import-path\">wootils/wootils/node/errorHandler.js</span>",
    "function"
  ],
  [
    "wootils/wootils/node/logger.js~logger",
    "variable/index.html#static-variable-logger",
    "<span>logger</span> <span class=\"search-result-import-path\">wootils/wootils/node/logger.js</span>",
    "variable"
  ],
  [
    "wootils/wootils/node/logger.js~loggerwithoptions",
    "function/index.html#static-function-loggerWithOptions",
    "<span>loggerWithOptions</span> <span class=\"search-result-import-path\">wootils/wootils/node/logger.js</span>",
    "function"
  ],
  [
    "wootils/wootils/node/packageinfo.js~packageinfo",
    "function/index.html#static-function-packageInfo",
    "<span>packageInfo</span> <span class=\"search-result-import-path\">wootils/wootils/node/packageInfo.js</span>",
    "function"
  ],
  [
    "wootils/wootils/node/packageinfo.js~packageinfoprovider",
    "variable/index.html#static-variable-packageInfoProvider",
    "<span>packageInfoProvider</span> <span class=\"search-result-import-path\">wootils/wootils/node/packageInfo.js</span>",
    "variable"
  ],
  [
    "wootils/wootils/node/pathutils.js~pathutils",
    "variable/index.html#static-variable-pathUtils",
    "<span>pathUtils</span> <span class=\"search-result-import-path\">wootils/wootils/node/pathUtils.js</span>",
    "variable"
  ],
  [
    "wootils/wootils/node/pathutils.js~pathutilswithhome",
    "function/index.html#static-function-pathUtilsWithHome",
    "<span>pathUtilsWithHome</span> <span class=\"search-result-import-path\">wootils/wootils/node/pathUtils.js</span>",
    "function"
  ],
  [
    "wootils/wootils/node/rootrequire.js~rootrequire",
    "function/index.html#static-function-rootRequire",
    "<span>rootRequire</span> <span class=\"search-result-import-path\">wootils/wootils/node/rootRequire.js</span>",
    "function"
  ],
  [
    "wootils/wootils/node/rootrequire.js~rootrequireprovider",
    "variable/index.html#static-variable-rootRequireProvider",
    "<span>rootRequireProvider</span> <span class=\"search-result-import-path\">wootils/wootils/node/rootRequire.js</span>",
    "variable"
  ],
  [
    "wootils/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "wootils/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "wootils/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "wootils/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "wootils/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "wootils/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "wootils/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "wootils/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "wootils/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "wootils/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "wootils/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "wootils/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "wootils/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "wootils/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "wootils/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "wootils/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "wootils/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "wootils/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "wootils/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "wootils/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "wootils/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "wootils/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "wootils/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "wootils/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "wootils/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "wootils/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "wootils/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "wootils/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "wootils/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "wootils/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "wootils/.external-ecmascript.js~String",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "wootils/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "wootils/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "wootils/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "wootils/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "wootils/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "wootils/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "wootils/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "wootils/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "wootils/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "wootils/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "wootils/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "wootils/.external-ecmascript.js~function",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "wootils/.external-ecmascript.js~null",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "wootils/.external-ecmascript.js~number",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "wootils/.external-ecmascript.js~object",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "wootils/.external-ecmascript.js~string",
    "external"
  ],
  [
    "wootils/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "wootils/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "wootils/node/appconfiguration.js",
    "file/wootils/node/appConfiguration.js.html",
    "wootils/node/appConfiguration.js",
    "file"
  ],
  [
    "wootils/node/appconfiguration.js~appconfiguration#activeconfiguration",
    "class/wootils/node/appConfiguration.js~AppConfiguration.html#instance-member-activeConfiguration",
    "wootils/node/appConfiguration.js~AppConfiguration#activeConfiguration",
    "member"
  ],
  [
    "wootils/node/appconfiguration.js~appconfiguration#allowconfigurationswitch",
    "class/wootils/node/appConfiguration.js~AppConfiguration.html#instance-member-allowConfigurationSwitch",
    "wootils/node/appConfiguration.js~AppConfiguration#allowConfigurationSwitch",
    "member"
  ],
  [
    "wootils/node/appconfiguration.js~appconfiguration#canswitch",
    "class/wootils/node/appConfiguration.js~AppConfiguration.html#instance-method-canSwitch",
    "wootils/node/appConfiguration.js~AppConfiguration#canSwitch",
    "method"
  ],
  [
    "wootils/node/appconfiguration.js~appconfiguration#configurations",
    "class/wootils/node/appConfiguration.js~AppConfiguration.html#instance-member-configurations",
    "wootils/node/appConfiguration.js~AppConfiguration#configurations",
    "member"
  ],
  [
    "wootils/node/appconfiguration.js~appconfiguration#constructor",
    "class/wootils/node/appConfiguration.js~AppConfiguration.html#instance-constructor-constructor",
    "wootils/node/appConfiguration.js~AppConfiguration#constructor",
    "method"
  ],
  [
    "wootils/node/appconfiguration.js~appconfiguration#environmentutils",
    "class/wootils/node/appConfiguration.js~AppConfiguration.html#instance-member-environmentUtils",
    "wootils/node/appConfiguration.js~AppConfiguration#environmentUtils",
    "member"
  ],
  [
    "wootils/node/appconfiguration.js~appconfiguration#get",
    "class/wootils/node/appConfiguration.js~AppConfiguration.html#instance-method-get",
    "wootils/node/appConfiguration.js~AppConfiguration#get",
    "method"
  ],
  [
    "wootils/node/appconfiguration.js~appconfiguration#getconfig",
    "class/wootils/node/appConfiguration.js~AppConfiguration.html#instance-method-getConfig",
    "wootils/node/appConfiguration.js~AppConfiguration#getConfig",
    "method"
  ],
  [
    "wootils/node/appconfiguration.js~appconfiguration#load",
    "class/wootils/node/appConfiguration.js~AppConfiguration.html#instance-method-load",
    "wootils/node/appConfiguration.js~AppConfiguration#load",
    "method"
  ],
  [
    "wootils/node/appconfiguration.js~appconfiguration#loadfromenvironment",
    "class/wootils/node/appConfiguration.js~AppConfiguration.html#instance-method-loadFromEnvironment",
    "wootils/node/appConfiguration.js~AppConfiguration#loadFromEnvironment",
    "method"
  ],
  [
    "wootils/node/appconfiguration.js~appconfiguration#loadfromfile",
    "class/wootils/node/appConfiguration.js~AppConfiguration.html#instance-method-loadFromFile",
    "wootils/node/appConfiguration.js~AppConfiguration#loadFromFile",
    "method"
  ],
  [
    "wootils/node/appconfiguration.js~appconfiguration#options",
    "class/wootils/node/appConfiguration.js~AppConfiguration.html#instance-member-options",
    "wootils/node/appConfiguration.js~AppConfiguration#options",
    "member"
  ],
  [
    "wootils/node/appconfiguration.js~appconfiguration#rootrequire",
    "class/wootils/node/appConfiguration.js~AppConfiguration.html#instance-member-rootRequire",
    "wootils/node/appConfiguration.js~AppConfiguration#rootRequire",
    "member"
  ],
  [
    "wootils/node/appconfiguration.js~appconfiguration#set",
    "class/wootils/node/appConfiguration.js~AppConfiguration.html#instance-method-set",
    "wootils/node/appConfiguration.js~AppConfiguration#set",
    "method"
  ],
  [
    "wootils/node/appconfiguration.js~appconfiguration#switch",
    "class/wootils/node/appConfiguration.js~AppConfiguration.html#instance-method-switch",
    "wootils/node/appConfiguration.js~AppConfiguration#switch",
    "method"
  ],
  [
    "wootils/node/appconfiguration.js~appconfigurationoptions",
    "typedef/index.html#static-typedef-AppConfigurationOptions",
    "wootils/node/appConfiguration.js~AppConfigurationOptions",
    "typedef"
  ],
  [
    "wootils/node/environmentutils.js",
    "file/wootils/node/environmentUtils.js.html",
    "wootils/node/environmentUtils.js",
    "file"
  ],
  [
    "wootils/node/environmentutils.js~environmentutils#constructor",
    "class/wootils/node/environmentUtils.js~EnvironmentUtils.html#instance-constructor-constructor",
    "wootils/node/environmentUtils.js~EnvironmentUtils#constructor",
    "method"
  ],
  [
    "wootils/node/environmentutils.js~environmentutils#development",
    "class/wootils/node/environmentUtils.js~EnvironmentUtils.html#instance-get-development",
    "wootils/node/environmentUtils.js~EnvironmentUtils#development",
    "member"
  ],
  [
    "wootils/node/environmentutils.js~environmentutils#env",
    "class/wootils/node/environmentUtils.js~EnvironmentUtils.html#instance-member-env",
    "wootils/node/environmentUtils.js~EnvironmentUtils#env",
    "member"
  ],
  [
    "wootils/node/environmentutils.js~environmentutils#get",
    "class/wootils/node/environmentUtils.js~EnvironmentUtils.html#instance-method-get",
    "wootils/node/environmentUtils.js~EnvironmentUtils#get",
    "method"
  ],
  [
    "wootils/node/environmentutils.js~environmentutils#production",
    "class/wootils/node/environmentUtils.js~EnvironmentUtils.html#instance-member-production",
    "wootils/node/environmentUtils.js~EnvironmentUtils#production",
    "member"
  ],
  [
    "wootils/node/errorhandler.js",
    "file/wootils/node/errorHandler.js.html",
    "wootils/node/errorHandler.js",
    "file"
  ],
  [
    "wootils/node/errorhandler.js~errorhandler#applogger",
    "class/wootils/node/errorHandler.js~ErrorHandler.html#instance-member-appLogger",
    "wootils/node/errorHandler.js~ErrorHandler#appLogger",
    "member"
  ],
  [
    "wootils/node/errorhandler.js~errorhandler#constructor",
    "class/wootils/node/errorHandler.js~ErrorHandler.html#instance-constructor-constructor",
    "wootils/node/errorHandler.js~ErrorHandler#constructor",
    "method"
  ],
  [
    "wootils/node/errorhandler.js~errorhandler#eventsnames",
    "class/wootils/node/errorHandler.js~ErrorHandler.html#instance-member-eventsNames",
    "wootils/node/errorHandler.js~ErrorHandler#eventsNames",
    "member"
  ],
  [
    "wootils/node/errorhandler.js~errorhandler#exitonerror",
    "class/wootils/node/errorHandler.js~ErrorHandler.html#instance-member-exitOnError",
    "wootils/node/errorHandler.js~ErrorHandler#exitOnError",
    "member"
  ],
  [
    "wootils/node/errorhandler.js~errorhandler#handle",
    "class/wootils/node/errorHandler.js~ErrorHandler.html#instance-method-handle",
    "wootils/node/errorHandler.js~ErrorHandler#handle",
    "method"
  ],
  [
    "wootils/node/errorhandler.js~errorhandler#listen",
    "class/wootils/node/errorHandler.js~ErrorHandler.html#instance-method-listen",
    "wootils/node/errorHandler.js~ErrorHandler#listen",
    "method"
  ],
  [
    "wootils/node/errorhandler.js~errorhandler#stoplistening",
    "class/wootils/node/errorHandler.js~ErrorHandler.html#instance-method-stopListening",
    "wootils/node/errorHandler.js~ErrorHandler#stopListening",
    "method"
  ],
  [
    "wootils/node/index.js",
    "file/wootils/node/index.js.html",
    "wootils/node/index.js",
    "file"
  ],
  [
    "wootils/node/logger.js",
    "file/wootils/node/logger.js.html",
    "wootils/node/logger.js",
    "file"
  ],
  [
    "wootils/node/logger.js~logger#constructor",
    "class/wootils/node/logger.js~Logger.html#instance-constructor-constructor",
    "wootils/node/logger.js~Logger#constructor",
    "method"
  ],
  [
    "wootils/node/logger.js~logger#error",
    "class/wootils/node/logger.js~Logger.html#instance-method-error",
    "wootils/node/logger.js~Logger#error",
    "method"
  ],
  [
    "wootils/node/logger.js~logger#info",
    "class/wootils/node/logger.js~Logger.html#instance-method-info",
    "wootils/node/logger.js~Logger#info",
    "method"
  ],
  [
    "wootils/node/logger.js~logger#log",
    "class/wootils/node/logger.js~Logger.html#instance-method-log",
    "wootils/node/logger.js~Logger#log",
    "method"
  ],
  [
    "wootils/node/logger.js~logger#messagesprefix",
    "class/wootils/node/logger.js~Logger.html#instance-member-messagesPrefix",
    "wootils/node/logger.js~Logger#messagesPrefix",
    "member"
  ],
  [
    "wootils/node/logger.js~logger#prefix",
    "class/wootils/node/logger.js~Logger.html#instance-method-prefix",
    "wootils/node/logger.js~Logger#prefix",
    "method"
  ],
  [
    "wootils/node/logger.js~logger#showtime",
    "class/wootils/node/logger.js~Logger.html#instance-member-showTime",
    "wootils/node/logger.js~Logger#showTime",
    "member"
  ],
  [
    "wootils/node/logger.js~logger#success",
    "class/wootils/node/logger.js~Logger.html#instance-method-success",
    "wootils/node/logger.js~Logger#success",
    "method"
  ],
  [
    "wootils/node/logger.js~logger#warning",
    "class/wootils/node/logger.js~Logger.html#instance-method-warning",
    "wootils/node/logger.js~Logger#warning",
    "method"
  ],
  [
    "wootils/node/packageinfo.js",
    "file/wootils/node/packageInfo.js.html",
    "wootils/node/packageInfo.js",
    "file"
  ],
  [
    "wootils/node/pathutils.js",
    "file/wootils/node/pathUtils.js.html",
    "wootils/node/pathUtils.js",
    "file"
  ],
  [
    "wootils/node/pathutils.js~pathutils#addlocation",
    "class/wootils/node/pathUtils.js~PathUtils.html#instance-method-addLocation",
    "wootils/node/pathUtils.js~PathUtils#addLocation",
    "method"
  ],
  [
    "wootils/node/pathutils.js~pathutils#app",
    "class/wootils/node/pathUtils.js~PathUtils.html#instance-get-app",
    "wootils/node/pathUtils.js~PathUtils#app",
    "member"
  ],
  [
    "wootils/node/pathutils.js~pathutils#constructor",
    "class/wootils/node/pathUtils.js~PathUtils.html#instance-constructor-constructor",
    "wootils/node/pathUtils.js~PathUtils#constructor",
    "method"
  ],
  [
    "wootils/node/pathutils.js~pathutils#getlocation",
    "class/wootils/node/pathUtils.js~PathUtils.html#instance-method-getLocation",
    "wootils/node/pathUtils.js~PathUtils#getLocation",
    "method"
  ],
  [
    "wootils/node/pathutils.js~pathutils#home",
    "class/wootils/node/pathUtils.js~PathUtils.html#instance-get-home",
    "wootils/node/pathUtils.js~PathUtils#home",
    "member"
  ],
  [
    "wootils/node/pathutils.js~pathutils#join",
    "class/wootils/node/pathUtils.js~PathUtils.html#instance-method-join",
    "wootils/node/pathUtils.js~PathUtils#join",
    "method"
  ],
  [
    "wootils/node/pathutils.js~pathutils#joinfrom",
    "class/wootils/node/pathUtils.js~PathUtils.html#instance-method-joinFrom",
    "wootils/node/pathUtils.js~PathUtils#joinFrom",
    "method"
  ],
  [
    "wootils/node/pathutils.js~pathutils#locations",
    "class/wootils/node/pathUtils.js~PathUtils.html#instance-member-locations",
    "wootils/node/pathUtils.js~PathUtils#locations",
    "member"
  ],
  [
    "wootils/node/pathutils.js~pathutils#path",
    "class/wootils/node/pathUtils.js~PathUtils.html#instance-member-path",
    "wootils/node/pathUtils.js~PathUtils#path",
    "member"
  ],
  [
    "wootils/node/providers.js",
    "file/wootils/node/providers.js.html",
    "wootils/node/providers.js",
    "file"
  ],
  [
    "wootils/node/rootrequire.js",
    "file/wootils/node/rootRequire.js.html",
    "wootils/node/rootRequire.js",
    "file"
  ],
  [
    "wootils/node/typedef.js",
    "file/wootils/node/typedef.js.html",
    "wootils/node/typedef.js",
    "file"
  ],
  [
    "wootils/node/typedef.js~jimple",
    "https://yarnpkg.com/en/package/jimple",
    "wootils/node/typedef.js~Jimple",
    "external"
  ],
  [
    "wootils/node/typedef.js~provider",
    "typedef/index.html#static-typedef-Provider",
    "wootils/node/typedef.js~Provider",
    "typedef"
  ],
  [
    "wootils/node/typedef.js~providerregistermethod",
    "typedef/index.html#static-typedef-ProviderRegisterMethod",
    "wootils/node/typedef.js~ProviderRegisterMethod",
    "typedef"
  ],
  [
    "wootils/shared/apiclient.js",
    "file/wootils/shared/apiClient.js.html",
    "wootils/shared/apiClient.js",
    "file"
  ],
  [
    "wootils/shared/apiclient.js~apiclient#authorizationtoken",
    "class/wootils/shared/apiClient.js~APIClient.html#instance-member-authorizationToken",
    "wootils/shared/apiClient.js~APIClient#authorizationToken",
    "member"
  ],
  [
    "wootils/shared/apiclient.js~apiclient#constructor",
    "class/wootils/shared/apiClient.js~APIClient.html#instance-constructor-constructor",
    "wootils/shared/apiClient.js~APIClient#constructor",
    "method"
  ],
  [
    "wootils/shared/apiclient.js~apiclient#defaultheaders",
    "class/wootils/shared/apiClient.js~APIClient.html#instance-member-defaultHeaders",
    "wootils/shared/apiClient.js~APIClient#defaultHeaders",
    "member"
  ],
  [
    "wootils/shared/apiclient.js~apiclient#delete",
    "class/wootils/shared/apiClient.js~APIClient.html#instance-method-delete",
    "wootils/shared/apiClient.js~APIClient#delete",
    "method"
  ],
  [
    "wootils/shared/apiclient.js~apiclient#endpoint",
    "class/wootils/shared/apiClient.js~APIClient.html#instance-method-endpoint",
    "wootils/shared/apiClient.js~APIClient#endpoint",
    "method"
  ],
  [
    "wootils/shared/apiclient.js~apiclient#endpoints",
    "class/wootils/shared/apiClient.js~APIClient.html#instance-member-endpoints",
    "wootils/shared/apiClient.js~APIClient#endpoints",
    "member"
  ],
  [
    "wootils/shared/apiclient.js~apiclient#error",
    "class/wootils/shared/apiClient.js~APIClient.html#instance-method-error",
    "wootils/shared/apiClient.js~APIClient#error",
    "method"
  ],
  [
    "wootils/shared/apiclient.js~apiclient#fetch",
    "class/wootils/shared/apiClient.js~APIClient.html#instance-method-fetch",
    "wootils/shared/apiClient.js~APIClient#fetch",
    "method"
  ],
  [
    "wootils/shared/apiclient.js~apiclient#fetchclient",
    "class/wootils/shared/apiClient.js~APIClient.html#instance-member-fetchClient",
    "wootils/shared/apiClient.js~APIClient#fetchClient",
    "member"
  ],
  [
    "wootils/shared/apiclient.js~apiclient#flattenendpoints",
    "class/wootils/shared/apiClient.js~APIClient.html#instance-method-flattenEndpoints",
    "wootils/shared/apiClient.js~APIClient#flattenEndpoints",
    "method"
  ],
  [
    "wootils/shared/apiclient.js~apiclient#get",
    "class/wootils/shared/apiClient.js~APIClient.html#instance-method-get",
    "wootils/shared/apiClient.js~APIClient#get",
    "method"
  ],
  [
    "wootils/shared/apiclient.js~apiclient#headers",
    "class/wootils/shared/apiClient.js~APIClient.html#instance-method-headers",
    "wootils/shared/apiClient.js~APIClient#headers",
    "method"
  ],
  [
    "wootils/shared/apiclient.js~apiclient#post",
    "class/wootils/shared/apiClient.js~APIClient.html#instance-method-post",
    "wootils/shared/apiClient.js~APIClient#post",
    "method"
  ],
  [
    "wootils/shared/apiclient.js~apiclient#put",
    "class/wootils/shared/apiClient.js~APIClient.html#instance-method-put",
    "wootils/shared/apiClient.js~APIClient#put",
    "method"
  ],
  [
    "wootils/shared/apiclient.js~apiclient#setauthorizationtoken",
    "class/wootils/shared/apiClient.js~APIClient.html#instance-method-setAuthorizationToken",
    "wootils/shared/apiClient.js~APIClient#setAuthorizationToken",
    "method"
  ],
  [
    "wootils/shared/apiclient.js~apiclient#setdefaultheaders",
    "class/wootils/shared/apiClient.js~APIClient.html#instance-method-setDefaultHeaders",
    "wootils/shared/apiClient.js~APIClient#setDefaultHeaders",
    "method"
  ],
  [
    "wootils/shared/apiclient.js~apiclient#url",
    "class/wootils/shared/apiClient.js~APIClient.html#instance-member-url",
    "wootils/shared/apiClient.js~APIClient#url",
    "member"
  ],
  [
    "wootils/shared/apiclient.js~apiclientendpoint",
    "typedef/index.html#static-typedef-APIClientEndpoint",
    "wootils/shared/apiClient.js~APIClientEndpoint",
    "typedef"
  ],
  [
    "wootils/shared/apiclient.js~apiclientendpoints",
    "typedef/index.html#static-typedef-APIClientEndpoints",
    "wootils/shared/apiClient.js~APIClientEndpoints",
    "typedef"
  ],
  [
    "wootils/shared/apiclient.js~fetchclient",
    "typedef/index.html#static-typedef-FetchClient",
    "wootils/shared/apiClient.js~FetchClient",
    "typedef"
  ],
  [
    "wootils/shared/apiclient.js~fetchoptions",
    "typedef/index.html#static-typedef-FetchOptions",
    "wootils/shared/apiClient.js~FetchOptions",
    "typedef"
  ],
  [
    "wootils/shared/deferred.js",
    "file/wootils/shared/deferred.js.html",
    "wootils/shared/deferred.js",
    "file"
  ],
  [
    "wootils/shared/eventshub.js",
    "file/wootils/shared/eventsHub.js.html",
    "wootils/shared/eventsHub.js",
    "file"
  ],
  [
    "wootils/shared/eventshub.js~eventshub#emit",
    "class/wootils/shared/eventsHub.js~EventsHub.html#instance-method-emit",
    "wootils/shared/eventsHub.js~EventsHub#emit",
    "method"
  ],
  [
    "wootils/shared/eventshub.js~eventshub#off",
    "class/wootils/shared/eventsHub.js~EventsHub.html#instance-method-off",
    "wootils/shared/eventsHub.js~EventsHub#off",
    "method"
  ],
  [
    "wootils/shared/eventshub.js~eventshub#on",
    "class/wootils/shared/eventsHub.js~EventsHub.html#instance-method-on",
    "wootils/shared/eventsHub.js~EventsHub#on",
    "method"
  ],
  [
    "wootils/shared/eventshub.js~eventshub#once",
    "class/wootils/shared/eventsHub.js~EventsHub.html#instance-method-once",
    "wootils/shared/eventsHub.js~EventsHub#once",
    "method"
  ],
  [
    "wootils/shared/eventshub.js~eventshub#reduce",
    "class/wootils/shared/eventsHub.js~EventsHub.html#instance-method-reduce",
    "wootils/shared/eventsHub.js~EventsHub#reduce",
    "method"
  ],
  [
    "wootils/shared/eventshub.js~eventshub#subscribers",
    "class/wootils/shared/eventsHub.js~EventsHub.html#instance-method-subscribers",
    "wootils/shared/eventsHub.js~EventsHub#subscribers",
    "method"
  ],
  [
    "wootils/shared/index.js",
    "file/wootils/shared/index.js.html",
    "wootils/shared/index.js",
    "file"
  ]
]